### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by hongbo-miao** [afitzek/hasura-metric-adapter#10]
Just an idea, it would be great to have a Grafana dashboard, so more people can use directly! 😃

A starter dashboard would be very helpful! And we can contribute more together in future!

https://grafana.com/grafana/dashboards/

**Comment by afitzek** [comment]
This would be really nice! Ready made dashboards help a lot to get started with such adapters to get a feeling for what metrics are exposed and how to read and handle them. In case you build one please let me know.

**Comment by afitzek** [comment]
I added an example dashboard to this repo: https://github.com/afitzek/hasura-metric-adapter/blob/main/example/grafana/dashboards/hasura-example-metrics.json

**Comment by hongbo-miao** [comment]
Thanks @afitzek ! 😃
