### ISSUE TITLE
Parse the operationName from the query document

### ISSUE THREAD

**Issue by subzero79** [afitzek/hasura-metric-adapter#24]
HI there, thanks for your contribution with this prometheus exporter. I saw your recording in the hasura community call.
I had a couple of issues starting it with latest version like this one #23 but i figure out i change the starting command to include the parameters.

Now I noticed in your video the operation name gets logged, so my first problem was that i wasn't seing any logs on operations name when not using the hasura console. So using the hasura console appends a property on the body with the operationName. 

On auto generated code for front-end request this is easy to fix as it just needs parsing of the document which can be done with the standard graphql library to obtain the operation name previous to the request(graphql-codegen react-query for example)

On the other side autogenerated server side queries/mutations like graphql-codegen with graphql-request the available middleware does not allow to inject extra properties(operationName) on the body. 

So the request is basically for the adapter to be able to parse the query field that has the document to obtain the operation name when operationName is not sent in the request.

Thanks

**Comment by subzero79** [comment]
Just an update on this, i just upgraded my server side graphql client to graphql-request to 5.0.0 and i noticed now you can pass middlewares and also now included the operationName by default.

In an codegen react-query fetcher the operationName can be obtained by using the graphql document parser. I'll leave an example here in case anyone needs it 

```ts
import useAppStore from "@/store/app-store/store";
import { parse } from "graphql";

export const fetchData = <TData, TVariables>(
	query: string,
	variables?: TVariables,
	options?: RequestInit["headers"]
): (() => Promise<TData>) => {
	const document = parse(query);
	let operationName = "Unknown";
	if (document.definitions.length > 0 && document.definitions[0].kind === "OperationDefinition") {
		operationName = document.definitions[0].name?.value;
	}
	return async () => {
		const token = useAppStore.getState().AUTH.userInfo.idToken;
		const res = await fetch(process.env.NEXT_PUBLIC_HASURA_URL, {
			method: "POST",
			// headers: { Authorization: `Bearer ${token}`, ...(options ?? {}) },
			headers: {
				"Content-Type": "application/json",
				...(options ?? {}),
				Authorization: `Bearer ${token}`,
			},
			body: JSON.stringify({
				operationName,
				query,
				variables,
			}),
		});

		const json = await res.json();

		if (json.errors) {
			const { message } = json.errors[0] || "Error..";
			if (message === "Could not verify JWT: JWTExpired") await useAppStore.getState().ACTIONS.refreshAuth();
			throw new Error(message);
		}

		return json.data;
	};
};
```

**Comment by efstathiosntonas** [comment]
@subzero79 Hi, how you fixed the params issue?

**Comment by subzero79** [comment]
> @subzero79 Hi, how you fixed the params issue?

You need to override the command for launching the adapter.

```yaml
hasura-metric-adapter:
  command: "/metrics --logfile /tmp/log/stdout.log"
```

In this case I use the image ghcr.io/afitzek/hasura-metric-adapter:v0.1.7
The latest image 0.1.8 has an extra parameter of --common-labels
