### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by 1fexd** [afitzek/hasura-metric-adapter#28]
Hi,

i am a bit lost. How do I get data in grafana? I have tried adding prometheus as datasource via `localhost:9000`, `localhost:9090`, `prometheus:9000` and `prometheus:9090` but none of those work. I am using your docker compose file. 

Kind regards

**Comment by fpiriz-inditex** [comment]
If I understood correctly, you are using the docker-compose file present in this repository as it is, but when you open grafana, no metrics are being depicted.

If you check the prometheus config file in the example folder, prometheus is already being scraped, so I may not understand your question, please, elaborate on the context and the error, please.

**Comment by 1fexd** [comment]
Oh, I must have overlooked the examples folder - my bad
