### ISSUE TITLE
Unable to work it out from Docker by using a shell script

### ISSUE THREAD

**Issue by shihab-geo** [afitzek/hasura-metric-adapter#35]
I am trying to run via docker using a shell script. Here's my shell-script as below:

`#!/bin/sh -
docker run -d \
       -e LISTEN_ADDR='http://localhost:9090' \
       -e LOG_FILE= '/var/lib/docker/containers/41bd65ff011d89fac1a86d4733e565ecf15ac0d4d0a60c49eb122dad8e96b3aa'  \
       -e HASURA_GRAPHQL_ENDPOINT='http://localhost:8080' \
       ghcr.io/afitzek/hasura-metric-adapter`
       

I am getting an error :
`docker: invalid reference format.`

Notes : 

1. I have pulled the docker image `ghcr.io/afitzek/hasura-metric-adapter` successfully on my server.
2. Hasura is running in a docker.
3. Postgres is already running
4. Grafana is already running.
5. Prometheus is already running.

But I am unable to run the `hasura-metric-adapter`.

**Comment by afitzek** [comment]
This error means that some other string in the docker command is interpreted as the docker image name. I don't have access to my computer within the next days to help you find the exact problem, but it has nothing to do with the metric adapter.
