### ISSUE TITLE
Unable to view the metrics

### ISSUE THREAD

**Issue by shihab-geo** [afitzek/hasura-metric-adapter#36]
I am able to run the docker image 'ghcr.io/afitzek/hasura-metric-adapter:latest' from the docker successfully. Here's the shell script:
`#!/bin/bash
docker run -d \
-e LISTEN_ADDR=0.0.0.0:9090 \
-e LOG_FILE=/var/lib/docker/containers/acda151de6dd8ac4ef6498/4rcdd8a32498-json.log \
-e HASURA_GRAPHQL_ENDPOINT=http://localhost:8080 \
ghcr.io/afitzek/hasura-metric-adapter:latest`

But, I am getting the below error in the 'ghcr.io/afitzek/hasura-metric-adapter:latest' container's log.
**error log:**
`ERROR metrics::logreader] File /var/lib/docker/containers/acda151de6dd8ac4ef6498/4rcdd8a32498-json.log could not be opened (No such file or directory (os error 2)). Will wait a little and then try again...`

**Note that**, I am getting Hasura's log from  `/var/lib/docker/containers/` , which is running in another docker container.

As a result, I am unable to view the metrics.

**Comment by afitzek** [comment]
The path `/var/lib/docker/containers/acda151de6dd8ac4ef6498/4rcdd8a32498-json.log` is a path on the host system and not in the container. You need to make sure that the container running the hasura adapter has access to this host file. You can for example volume mount it using the `-v` flag of the docker cli.

This is not really a problem with the adapter. So I'm closing this issue.
