### ISSUE TITLE
Grafana dashboard publication

### ISSUE THREAD

**Issue by jjangga0214** [afitzek/hasura-metric-adapter#41]
Hi!

I've seen https://github.com/afitzek/hasura-metric-adapter/issues/10#issuecomment-1320815006

Would you consider officially publishing the dashboard (as-is or with a bit of enhancement) to https://grafana.com/grafana/dashboards/?

Then people will be able to install the dashboard very easily.

Thanks :)

**Comment by afitzek** [comment]
@jjangga0214 Sorry for the late reply, yeah that is a good idea :+1: , I just tried it, seems like I have to convert it to a new json format to upload it there. I'll look into that

**Comment by jjangga0214** [comment]
Great! I am looking forward to it! Thanks :)

**Comment by afitzek** [comment]
I published it here: https://grafana.com/grafana/dashboards/20180 It seems like it is not available yet, probably has to be synced in somehow.

**Comment by jjangga0214** [comment]
Thank you so much!
Though it's currently 404 as you said, I will try later.
Great job :)
