### ISSUE TITLE
thread 'main' panicked at 'required', src/main.rs:123:67

### ISSUE THREAD

**Issue by hongbo-miao** [afitzek/hasura-metric-adapter#5]
Hi @afitzek thanks for this cool project to expose Hasura metrics endpoint!

I tried to set up, however, I got error

```sh
thread 'main' panicked at 'required', src/main.rs:123:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

for this sidecar container.

Here is my pull request to add **hasura-metric-adapter**: https://github.com/Hongbo-Miao/hongbomiao.com/pull/4802/files#diff-5fbfb2b267bf990e8c4f7951d958559b4e711c578bc235b0b53b7e86dfe78349

Any idea? Thanks!

**Comment by afitzek** [comment]
Hi @Hongbo-Miao
Cool to see that someone else is also using it. ;) 

Sorry I should update the readme, there are 2 more required envvars:
- `HASURA_GRAPHQL_ADMIN_SECRET`, this should be the admin secret of hasura
- `HASURA_GRAPHQL_ENDPOINT`, this should be the endpoint of hasura without path, it defaults to `http://localhost:8080`

These were added to expose the metrics about events as well. (I also need to add them to the Readme).

**Comment by afitzek** [comment]
I just updated the readme to contain this information.

**Comment by hongbo-miao** [comment]
Thanks Andreas, now it can deploy! 😊
